# DEVELOPMENT compose file
# Just run `docker compose up --build` to run the app on port 8000
version: "3.3"

services:
  backend:
    env_file:
      - "dev.env"
    environment:
      MODULE_NAME: server
      VARIABLE_NAME: app
    build:
      context: .
      dockerfile: server.Dockerfile
      args:
        IS_PRODUCTION: "${IS_PRODUCTION-false}"
    volumes:
      # Sync changes made during development are automatically reflected in the container
      - ".:/app"
      - "backend-log:${LOG_DIR-/var/tusky/}"
    depends_on:
      - "db"
    command: "/start-reload.sh"
    ports:
      - "8007:80"
    links:
      - db

  db:
    image: postgres:13
    volumes:
    - db-data:/var/lib/postgresql/data/
    env_file:
      - dev.env



volumes:
  db-data:
  backend-log:
